# Generated by Django 5.0.4 on 2024-04-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite', to='books.customuser'),
        ),
    ]
