# Generated by Django 5.0.4 on 2024-04-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
