# Generated by Django 5.0.4 on 2024-04-29 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_publication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='favourite',
        ),
        migrations.RemoveField(
            model_name='book',
            name='favourites',
        ),
    ]
