# Generated by Django 4.2.7 on 2024-05-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
