# Generated by Django 5.0.4 on 2024-05-04 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
